#!/usr/bin/env zsh
set -eu
backend_dir="$(cd "$(dirname "$0")";pwd)/lib"

ssh-config-generate(){
	ssh_config=~/.ssh/config
	rm -f "$ssh_config"
	()( umask 077; :>"$ssh_config"; )
	find ~/.ssh/config.d -type f ! -name '.*' |
		grep '[0-9]\+[^/]\+$' |
		sort |
		xargs "$backend_dir/convertor.py" >"$ssh_config"
}
ssh-config-generate

