#!/usr/bin/env zsh
set -eu
backend_dir="$(cd "$(dirname "$0")";pwd)/lib"

ssh-config-generate(){
#     ssh_config=/tmp/.$USER.ssh_config
#     rm -f "$ssh_config"
#     ()( umask 077; :>"$ssh_config"; )
	find ~/.ssh/config.d -type f ! -name '.*' | sort | xargs cat #"$backend_dir/convertor.py" #>"$ssh_config"
#     if ! [ -L ~/.ssh/config ]; then
#         rm -f ~/.ssh/config
#         ln -s "$ssh_config" ~/.ssh/config
#     fi
}
ssh-config-generate

